[Audio]
Volume=100

[General]
ColorScheme=Breeze Dark
GuiStyle=Fusion
LastPlayedFile=file:///home/localguru/ASMR Gentle Ear Blowing for Deep Sleep (No Talking) ｜ Tangerin %5BQ7qJElVki4Y%5D.webm
RememberWindowGeometry=true

[Playlist]
RandomPlayback=true
